name: Shopify Theme Preview

on: pull_request

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Install packages
        run: yarn install

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler: 'latest'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Production Build
        run: yarn webpack:build:prod

      - name: Theme deploy
        id: theme-deploy
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.THEME_ACCESS }}
          SHOPIFY_FLAG_STORE: ${{ vars.SHOPIFY_URL }}
          SHOPIFY_FLAG_PATH: './src'
          SHOPIFY_CLI_TTY: 0
        run: |
          THEME_DEPLOY=$(shopify theme push --development --json 2>&1)
          echo "MESSAGE=$THEME_DEPLOY" >> $GITHUB_OUTPUT

      - name: PR Comment
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Theme preview url: ${{ fromJson(steps.theme-deploy.outputs.MESSAGE).theme.preview_url }} \n Theme editor url: ${{ fromJson(steps.theme-deploy.outputs.MESSAGE).theme.editor_url }}" }'
